apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "uiapikms.fullname" . }}-api
  labels:
    app: {{ include "uiapikms.name" . }}
    component: api
spec:
  replicas: {{ .Values.autoscaling.minReplicas }}
  selector:
    matchLabels:
      app: {{ include "uiapikms.name" . }}
      component: api
  template:
    metadata:
      labels:
        app: {{ include "uiapikms.name" . }}
        component: api
    spec:
      containers:
        - name: api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: DATABASE_URL
              value: "postgres://{{ .Values.postgres.user }}:$(POSTGRES_PASSWORD)@{{ .Values.postgres.host }}:5432/{{ .Values.postgres.db }}"
            - name: AZURE_KEY_VAULT_URI
              value: {{ .Values.keyVault.uri | quote }}
          envFrom:
            - secretRef:
                name: {{ .Values.postgres.passwordSecret }}
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /healthz
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /healthz
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          resources: {{- toYaml .Values.resources | nindent 12 }}
